### PR TITLE
Rename Workflows to Dispatch.

### PR DESCRIPTION
**Pull request by tbedford**
## Description

- [x] Rename Workflows to Dispatch
- [ ] Test scripts (can only be done after 11.00 UTC (Noon BST) 9th October 2019)

### CODE REVIEW

**Review by AlexLakatos — APPROVED** [review]
LGTM 💾

**Comment by AlexLakatos** [comment]
I think we need to update the folder names as well so people who land here don't get confused. And we need to update the method names as well to account for the upcoming Node library changes in https://github.com/Nexmo/nexmo-node/pull/207

**Comment by tbedford** [comment]
@AlexLakatos: are you OK with this now?

**Comment by AlexLakatos** [comment]
LGTM, let me just release the beta so we can test them out. 🏖

**Pull request merged**
