### PR TITLE
add missing conversation code snippets

### PR DESCRIPTION
**Pull request by AlexLakatos**

### CODE REVIEW

**Comment by tbedford** [comment]
Alex, before merging I wanted to check, is this for the current Conversation API, or should this only be merged once we switch to Conversation API v2? Thanks!

**Comment by AlexLakatos** [comment]
It's for the current implementation on nexmo@beta, with some endpoints
using beta, and some already using beta2 (list paginated endpoints)

**Comment by tbedford** [comment]
I will need to create a PR for NDP to test again this.

**Comment by AlexLakatos** [comment]
I have a PR in the works already, give me a bit to get to the airport and
I'll PR NDP as well.

**Comment by tbedford** [comment]
Oh, I already did it...

**Review by tbedford — APPROVED** [review]

**Pull request merged**
